# Welcome to Jekyll!
#

# Site settings
title: StrikeSim
description: |
  Introducing the worldâ€™s first strike planning simulation tool
owner: StrikeSim # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: teamStrikeSim@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://StrikeSim.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/StrikeSim
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/StrikeSim
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: mailto:teamstrikesim@gmail.com
  #flickr:
  instagram: https://instagram.com/StrikeSim
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
